kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
  - go test ./...

# - name: publish
#   image: plugins/docker
#   settings:
#     auto_tag: true
#     repo: jsussman/drone-validator
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
